#ifndef _TOKEN_H_
#define _TOKEN_H_



struct alpha_token_t{

	int lineno;
	int type;
	int int_value;
	double d_value;
	char * s_value;
};	

typedef struct alpha_token_t* ALP;
enum TYPE {
			 ENDOF=40,INTCONST, FLOATCONST,STRING,ID,IF_KEYWORD,FOR_KEYWORD,ELSE_KEYWORD,
 			 FUNCTION_KEYWORD,WHILE_KEYWORD,RETURN_KEYWORD,BREAK_KEYWORD,CONTINUE_KEYWORD,
			 LOCAL_KEYWORD,TRUE_KEYWORD,FALSE_KEYWORD,NIL_KEYWORD,AND_KEYWORD,OR_KEYWORD,
			 NOT_KEYWORD,GLOBAL_KEYWORD,PLUSPLUS_OP,SUBSUB_OP,MULL_OP,	DIV_OP,EQ_OP,PLUS_OP,
			 SUB_OP,ASS_OP,NEQ_OP,MOD_OP,GEQ_OP,LEQ_OP,GRE_OP,LESS_OP,L_PAR,R_PAR,L_AG,R_AG,
			 R_BR,L_BR,COMMA,SEMICOL,FULLST,D_FULLST,ILLEGAL	
		 
		 };



#endif
